### PR TITLE
Add Dock Vendor

### PR DESCRIPTION
**Pull request by SamHellawell**
plugfest2020 support for Dock's implementation of the W3 VC Data model API

https://github.com/docknetwork/vc-api

### CODE REVIEW

**Comment by OR13** [comment]
@SamHellawell  thanks! after this PR is merged, please open a PR that updates the test report to include your vendor.

**Comment by SamHellawell** [comment]
@OR13 thanks for the quick review!

i can just commit that here if you like, wasn't sure if you wanted it committing in the repo or if it was auto generated

**Comment by OR13** [comment]
@SamHellawell I appreciate you keeping it in a separate PR, for review-ability... someday we will hook it up to CI, making this unnecessary.

**Comment by SamHellawell** [comment]
no worries, can do that

**Comment by gannan08** [comment]
> @SamHellawell I appreciate you keeping it in a separate PR, for review-ability... someday we will hook it up to CI, making this unnecessary.

@OR13 Did someone say "CI"  👀 ? I can take a look at hooking up automating the test report.

**Comment by OR13** [comment]
@gannan08 here is how to do it with github pages hosting : )

https://github.com/decentralized-identity/sidetree/blob/master/.github/workflows/deploy-spec.yml

**Comment by OR13** [comment]
@SamHellawell thanks for your contribution, please feel free to open a PR that will update: https://w3c-ccg.github.io/vc-examples/plugfest-2020.html

to include your vendor.

**Pull request merged**
